collection @boletim, object_root: false
attributes :id,
           :disciplina,
           :nac1,
           :nacs1,
           :am1,
           :ps1,
           :md1,
           :nac2,
           :nacs2,
           :am2,
           :ps2,
           :md2,
           :aulas,
           :faltas1,
           :faltas2,
           :presenca,
           :mp,
           :exame,
           :mf,
           :situacao
